//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.18 at 06:42:10 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://www.sat.gob.mx/cfd/4", 
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns = {
        @XmlNs(prefix = "cfdi", namespaceURI = "http://www.sat.gob.mx/cfd/4"),
        @XmlNs(prefix = "pago20", namespaceURI = "http://www.sat.gob.mx/Pagos20"),
    }
    )
package com.cfdi4.comprobante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlNs;