---
grails:
    profile: rest-api
    codegen:
        defaultPackage: sx.compras
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    dbCreate: ''
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=true
            #url: jdbc:mysql://10.10.1.225:3306/rescue?autoReconnect=true
            username: root
            password: sys
    test:
        dataSource:
            dbCreate: none
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: sNa
            password:
    production:
        dataSource:
            dbCreate: none
            #url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
            url: jdbc:mysql://${JDBC_CONNECTION_STRING}?autoReconnect=true
            username: root
            password: sys
            properties:
                maxActive: 10
                maxIdle: 10
                minIdle: 3
                initialSize: 3
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                maxWait: 10000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
    contabilidad:
            dataSource:
                dbCreate: none
                #url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
                url: jdbc:mysql://${JDBC_CONNECTION_STRING}?autoReconnect=true
                username: root
                password: sys
                properties:
                    maxActive: 10
                    maxIdle: 10
                    minIdle: 3
                    initialSize: 3
                    minEvictableIdleTimeMillis: 1800000
                    timeBetweenEvictionRunsMillis: 1800000
                    numTestsPerEvictionRun: 3
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: true
                    maxWait: 10000
                    validationQuery: 'SELECT 1'
                    validationQueryTimeout: 3
                    validationInterval: 15000
    tesoreria:
            dataSource:
                dbCreate: none
                url: jdbc:mysql://${JDBC_CONNECTION_STRING}?autoReconnect=true
                #url: jdbc:mysql://10.10.1.229/siipapx_dev?autoReconnect=true
                username: root
                password: sys
                properties:
                    maxActive: 10
                    maxIdle: 10
                    minIdle: 3
                    initialSize: 3
                    minEvictableIdleTimeMillis: 1800000
                    timeBetweenEvictionRunsMillis: 1800000
                    numTestsPerEvictionRun: 3
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: true
                    maxWait: 10000
                    validationQuery: 'SELECT 1'
                    validationQueryTimeout: 3
                    validationInterval: 15000
    compras:
            dataSource:
                dbCreate: none
                url: jdbc:mysql://${JDBC_CONNECTION_STRING}?autoReconnect=true
                username: root
                password: sys
                properties:
                    maxActive: 10
                    maxIdle: 10
                    minIdle: 3
                    initialSize: 3
                    minEvictableIdleTimeMillis: 1800000
                    timeBetweenEvictionRunsMillis: 1800000
                    numTestsPerEvictionRun: 3
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: true
                    maxWait: 10000
                    validationQuery: 'SELECT 1'
                    validationQueryTimeout: 3
                    validationInterval: 15000                    
    certificacion:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/siipapx_oficinas?autoReconnect=false
            username: root
            password: sys
            properties:
                maxActive: 10
                maxIdle: 10
                minIdle: 3
                initialSize: 3
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                maxWait: 10000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
---
server:
  port: 9195
  contextPath: /siipapx
---
environments:
    certificacion:
        server:
            port: 9199
    contabilidad:
        server:
            port: 9290
    tesoreria:
        server:
            port: 9490

---
grails:
    cors:
        enabled: true
---
siipapx:
  econta:
    polizasDir: /home/econta/polizas
  logistica:
    inicioOperacionComisiones: 01/03/2019
---
environments:
  development:
    siipapx:
      cxp:
        cfdisDir: /Users/rubencancino/Documents/cfdis-carga/compras
        gastosDir: /Users/rubencancino/Documents/cfdis-carga/gastos
        comisionesDir: /Users/rubencancino/Documents/cfdis-carga/comisiones
        honorariosDir: /Users/rubencancino/Documents/cfdis-carga/honorarios
      econta:
        xmlDir: ${user.home}/.econta
        polizasDir: ${user.home}/Documents/econta
      cfdi:
        dir: ${user.home}/Documents/siipapx-cfdis
      logistica:
        inicioOperacionComisiones: 01/03/2019
      sat:
        metadata: ${user.home}/cfdis/metadata
  production:
    siipapx:
      cxp:
        cfdisDir: /home/cfdProv
        gastosDir: /home/cfdGastos
      cfdi:
        dir: /home/siipapx-cfdis
  compras:
    siipapx:
      cxp:
        cfdisDir: /home/cfdProv
        gastosDir: /home/cfdGastos
      cfdi:
        dir: /home/siipapx-cfdis
  contabilidad:
    siipapx:
      sat:
        metadata: /home/metadata
      econta:
        xmlDir: /home/econta
  tesoreria:
    siipapx:
      cxp:
        cfdisDir: /home/cfdProv
        gastosDir: /home/cfdGastos
        comisionesDir: /home/cfdiComisiones
        honorariosDir: /home/cfdiHonorarios
---
quartz:
    autoStartup: false
---
environments:
  development:
    siipapx:
      firebase:
        projectId: siipapx-436ce
        url: https://siipapx-436ce.firebaseio.com
        bucket: siipapx-436ce.appspot.com
  certificacion:
    siipapx:
      firebase:
        projectId: siipapx-436ce
        url: https://siipapx-436ce.firebaseio.com
        bucket: siipapx-436ce.appspot.com
  compras:
    siipapx:
      firebase:
        projectId: siipapx-51354
        url: https://siipapx-51354.firebaseio.com
        bucket: siipapx-51354.appspot.com
  production:
    siipapx:
      firebase:
        projectId: siipapx-51354
        url: https://siipapx-51354.firebaseio.com
        bucket: siipapx-51354.appspot.com
---