//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.20 at 09:10:07 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/sitio_internet/cfd")
package com.cfdi4.cancelacion;
